string leftHand_action   # Paper,   Wave,   One, Two, Three, Rock
string rightHand_action  # Paper,   Wave,   One, Two, Three, Rock
---
bool success   # indicate successful run of triggered service
string message # informational