# NLUService.srv

# 请求部分
string raw_input        # 原始输入文本
bool enable_context     # 启用上下文理解
bool enable_save        # 是否记录
string context_id       # 会话上下文ID

---
# 响应部分
int32 status            # 返回的状态码
nlu_result[] nlu_result  # NLU 识别结果
